// <auto-generated />
using System;
using Hoteis.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoteis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123162010_novoBD")]
    partial class novoBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoteis.API.Model.Hospede", b =>
                {
                    b.Property<int>("Id_hospede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_hospede"));

                    b.Property<string>("CPF_hospede")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Email_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Menor_idade")
                        .HasColumnType("bit");

                    b.Property<string>("Nome_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_hospede");

                    b.HasIndex("CPF_hospede")
                        .IsUnique();

                    b.ToTable("hospedes");
                });

            modelBuilder.Entity("Hoteis.API.Model.Quarto", b =>
                {
                    b.Property<int>("Id_quarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_quarto"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descrição")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero_quarto")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_quarto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_quarto");

                    b.ToTable("quartos");
                });

            modelBuilder.Entity("Hoteis.API.Model.Reserva", b =>
                {
                    b.Property<int>("Id_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reserva"));

                    b.Property<string>("Contato_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_saida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HospedeId_hospede")
                        .HasColumnType("int");

                    b.Property<string>("Nome_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade_hospedes")
                        .HasColumnType("int");

                    b.Property<int>("Quarto_ID_FK")
                        .HasColumnType("int");

                    b.HasKey("Id_reserva");

                    b.HasIndex("HospedeId_hospede");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("Hoteis.API.Model.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Email_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha_Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_user")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Hoteis.API.Model.Reserva", b =>
                {
                    b.HasOne("Hoteis.API.Model.Hospede", null)
                        .WithMany("reservas")
                        .HasForeignKey("HospedeId_hospede");
                });

            modelBuilder.Entity("Hoteis.API.Model.Hospede", b =>
                {
                    b.Navigation("reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
