// <auto-generated />
using System;
using Hoteis.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoteis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hoteis.API.Model.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Nome_Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Hoteis.API.Model.Quarto", b =>
                {
                    b.Property<int>("Id_quarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_quarto"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("Categoria_ID_FK")
                        .HasColumnType("int");

                    b.Property<string>("Descrição")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero_quarto")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_quarto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_quarto");

                    b.ToTable("quartos");
                });

            modelBuilder.Entity("Hoteis.API.Model.Reserva", b =>
                {
                    b.Property<int>("Id_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_reserva"));

                    b.Property<string>("Contato_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_saida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_hospede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco_total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade_hospedes")
                        .HasColumnType("int");

                    b.Property<int>("Quarto_ID_FK")
                        .HasColumnType("int");

                    b.HasKey("Id_reserva");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("Hoteis.API.Model.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Email_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha_Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_user")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
